# Generated by Django 6.0.6 on 2026-06-29 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="teams.workspace",
            ),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="documentcomparison",
            name="document_base",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comparisons_as_base",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="documentcomparison",
            name="document_compare",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comparisons_as_compare",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="documentcomparison",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_comparisons",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documenttranslation",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="folder",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="documents.folder",
            ),
        ),
        migrations.AddField(
            model_name="folder",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="folder",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="folders",
                to="teams.workspace",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="documents.folder",
            ),
        ),
        migrations.AddField(
            model_name="highlight",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="highlights",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="highlight",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="highlight",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="note",
                to="documents.highlight",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bookmark",
            unique_together={("document", "user", "page_number")},
        ),
        migrations.AlterUniqueTogether(
            name="documentcomparison",
            unique_together={("user", "document_base", "document_compare")},
        ),
        migrations.AlterUniqueTogether(
            name="documenttranslation",
            unique_together={("document", "language")},
        ),
        migrations.AddConstraint(
            model_name="folder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("workspace__isnull", False)),
                fields=("workspace", "name", "parent"),
                name="unique_folder_name_per_workspace",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="folder",
            unique_together={("user", "name", "parent")},
        ),
    ]
