# Generated by Django 6.0.6 on 2026-06-11 12:37

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_document_processed_at_document_summary_long_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(upload_to=documents.models.document_upload_path),
        ),
    ]
