# Generated by Django 6.0.6 on 2026-06-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_folder_document_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
