# Generated by Django 6.0.6 on 2026-06-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_documenttranslation"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="faqs",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="key_points",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="rewrite_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="rewrite_style",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
