# Generated by Django 6.0.6 on 2026-06-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0007_document_rewrite_keypoints_faqs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="rewrite_style",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
