# Generated by Django 6.0.6 on 2026-06-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0010_highlight_note_bookmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="extraction_method",
            field=models.CharField(
                choices=[
                    ("native", "Native Text"),
                    ("ocr", "OCR"),
                    ("mixed", "Mixed (Native + OCR)"),
                ],
                default="native",
                max_length=10,
            ),
        ),
    ]
